import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className='container mx-auto px-10 py-5 max-w-4xl'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='text-4xl'>H1</h1>
        <button className="btn">Button</button>
      </main>
    </div>
  )
}

export default Home
